[build]
  command = "npm run build:netlify"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/file/*"
  function = "proxy"

[[redirects]]
  from = "/api/news/detail"
  to = "/.netlify/functions/news-detail"
  status = 200

[[redirects]]
  from = "/api/news"
  to = "/.netlify/functions/news"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
